development:
  lang: 'pt'
  connect: 'http://connect:8080'
  connect_url: 'http://localhost:8080'
  couchdb: 'http://couchdb:5984'
  elasticsearch: 'http://elasticsearch:9200'
  floradata: "http://floradata:80"
  servicos: "http://servicos.jbrj.gov.br/flora/endemism/"
test:
  lang: 'pt'
  connect: 'http://connect'
  connect_url: 'http://connect'
  couchdb: 'http://couchdb:5984'
  elasticsearch: 'http://elasticsearch:9200'
  db: 'cncflora_test'
  floradata: "http://floradata:80"
  servicos: "http://servicos.jbrj.gov.br/flora/endemism/"
production:
  lang: 'pt'
  connect: 'http://connect'
  connect_url: 'http://$HOST/connect'
  couchdb: 'http://couchdb:5984'
  elasticsearch: 'http://elasticsearch:9200'
  base: '/profiles'
  floradata: "http://floradata:80"
  occurrences_url: "http://$HOST/occurrences"
  assessments_url: "http://$HOST/assessments"
  servicos: "http://servicos.jbrj.gov.br/flora/endemism/"
