development:
  lang: 'pt'
  connect: 'http://192.168.50.10:8080'
  connect_url: 'http://192.168.50.10:8080'
  couchdb: 'http://192.168.50.10:5984'
  elasticsearch: 'http://192.168.50.10:9200'
test:
  lang: 'pt'
  connect: 'http://192.168.50.10:8080'
  connect_url: 'http://192.168.50.10:8080'
  couchdb: 'http://192.168.50.10:5984'
  elasticsearch: 'http://192.168.50.10:9200'
  db: 'cncflora_test'
production:
  lang: 'pt'
  connect: 'http://$HOST/connect'
  connect_url: 'http://cncflora.jbrj.gov.br/connect'
  couchdb: 'http://$HOST/couchdb'
  elasticsearch: 'http://$HOST/elasticsearch'
  base: '/profiles'
  occurrences: "http://$HOST/occurrences"
  occurrences_url: "http://cncflora.jbrj.gov.br/occurrences"
  assessments: "http://$HOST/assessments"
  assessments_url: "http://cncflora.jbrj.gov.br/assessments"
