development:
  lang: 'pt'
  connect: 'http://connect:8080'
  connect_url: 'http://localhost:8080'
  couchdb: 'http://couchdb:5984'
  elasticsearch: 'http://elasticsearch:9200'
test:
  lang: 'pt'
  connect: 'http://connect:8080'
  connect_url: 'http://connect:8080'
  couchdb: 'http://couchdb:5984'
  elasticsearch: 'http://elasticsearch:9200'
  db: 'cncflora_test'
homolog:
  lang: 'pt'
  connect: 'http://jb048/connect'
  connect_url: 'http://jb048/connect'
  couchdb: 'http://jb048:5984'
  elasticsearch: 'http://jb048:9200'
  base: '/profiles'
  occurrences_url: "http://$HOST/occurrences"
  assessments_url: "http://$HOST/assessments"
production:
  lang: 'pt'
  connect: 'http://jb049/connect'
  connect_url: 'http://cncflora.jbrj.gov.br/connect'
  couchdb: 'http://jb049:5984'
  elasticsearch: 'http://jb049:9200'
  base: '/profiles'
  occurrences_url: "http://$HOST/occurrences"
  assessments_url: "http://$HOST/assessments"
