development:
  lang: 'pt'
  connect: 'http://connect:8080'
  connect_url: 'http://localhost:8080'
  couchdb: 'http://couchdb:5984'
  elasticsearch: 'http://elasticsearch:9200'
test:
  lang: 'pt'
  connect: 'http://connect:8080'
  connect_url: 'http://localhost:8080'
  couchdb: 'http://couchdb:5984'
  elasticsearch: 'http://elasticsearch:9200'
  db: 'cncflora_test'
production:
  lang: 'pt'
  connect: 'http://$HOST/connect'
  connect_url: 'http://cncflora.jbrj.gov.br/connect'
  couchdb: 'http://$HOST/couchdb'
  elasticsearch: 'http://$HOST/elasticsearch'
  base: '/profiles'
  occurrences: "http://$HOST/occurrences"
  occurrences_url: "http://cncflora.jbrj.gov.br/occurrences"
  assessments: "http://$HOST/assessments"
  assessments_url: "http://cncflora.jbrj.gov.br/assessments"
