profilesprod:
    build: .
    ports:
      - "8888:80"
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
    environment:
        - PHP_ENV=test
elasticsearch:
    image: cncflora/elasticsearch
    ports:
        - 9200
    volumes:
        - /var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw
couchdb:
    image: cncflora/couchdb
    ports:
        - 5984
    volumes:
        - /var/data/couchdb:/var/lib/couchdb:rw
connect:
    image: cncflora/connect
    ports:
        - 80
    volumes:
        - "/var/data/connect:/var/floraconnect:rw"
selenium:
    image: cncflora/selenium
    links:
        - profilesprod:profiles
        - connect:connect
    ports:
        - "4444:4444"
        - "5900:5900"
tester:
    image: cncflora/apache
    volumes:
        - .:/var/www
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - selenium:selenium
        - profilesprod:profiles
    environment:
        - PHP_ENV=test
