Feature: Move profile on workflow

    Scenario: Move profile around 
        Given I am on "/cncflora_test/specie/Aphelandra longiflora"
        Then I login as "Diogo", "diogo@cncflora.net", "cncflora_test", "admin,analyst,sig,validator", "ACANTHACEAE"
        And I press "create-btn"
        And I wait 4000
        And I press "Salvar"
        And I wait 4000
        Then I should see "Status: open"
        And I follow "Editar"
        Then I press "Enviar para GIS"
        Then I should see "Status: sig"
        Then I follow "GIS"
        Then I press "Voltar para análise"
        Then I should see "Status: open"
        Then I follow "Editar"
        Then I press "Enviar para GIS"
        Then I follow "GIS"
        Then I press "Enviar para validação"
        Then I should see "Status: validation"
        Then I follow "Comunicação"
        Then I press "Voltar para análise"
        Then I should see "Status: open"
        Then I follow "Editar"
        Then I press "Enviar para GIS"
        Then I follow "GIS"
        Then I press "Enviar para validação"
        Then I follow "Validar"
        Then I press "Enviar para revisão"
        Then I should see "Status: review"
        Then I follow "Revisar"
        Then I press "Enviar para GIS"
        Then I should see "Status: review-sig"
        Then I follow "GIS"
        Then I press "Voltar para análise"
        Then I should see "Status: review"
        Then I follow "Revisar"
        Then I press "Enviar para GIS"
        Then I follow "GIS"
        Then I press "Concluir"
        Then I should see "Status: done"

